/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matakuliah;

import java.sql.*;
import javax.swing.JOptionPane;

public class FormMataKuliah extends javax.swing.JFrame {

    Connection con;
    String url, db, driver, user;
    String ikdmk, imatkul, isks;
    public Statement stat;
    public ResultSet rs;
    
    public void connect(){
        con = null;
        url = "jdbc:mysql://localhost:3306/";db="kuliah";
        driver = "com.mysql.jdbc.Driver";
        try{
            Class.forName(driver);
        } catch (ClassNotFoundException cnfe){
            System.err.println("Class driver tidak ada : " + cnfe.getMessage());
        }
    }
    
    public void bersih(){
        kdmk.setText("");
        matkul.setText("");
        sks.setText("");
        kdmk.requestFocus();
    }
    public FormMataKuliah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kdmk = new javax.swing.JTextField();
        matkul = new javax.swing.JTextField();
        sks = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI MATA KULIAH ");

        jLabel2.setText("Kode Mata Kuliah");

        jLabel3.setText("Mata Kuliah");

        jLabel4.setText("SKS");

        kdmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdmkActionPerformed(evt);
            }
        });

        sks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sksActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sks, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kdmk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kdmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(sks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sksActionPerformed

    private void kdmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdmkActionPerformed
        connect();
        try{
            con = DriverManager.getConnection(url+db,"root","");
            stat = con.createStatement();
            String kode = "select * from mtkuliah where kdmk='"+kdmk.getText()+"'";
            rs.beforeFirst();
            if (rs.next()) {
                matkul.setText(rs.getString("matkul"));
                sks.setText(rs.getString("sks"));
            }
            else{
                JOptionPane.showMessageDialog(this, "Maaf Data Tidak Ditemukan",
                        "Infromation",JOptionPane.INFORMATION_MESSAGE);
                bersih();
                kdmk.requestFocus();
            }
        } catch (SQLException se){
            System.err.println("Terjadi Kesalahan Perintah SQL : " + se.getMessage());
        }
    }//GEN-LAST:event_kdmkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bersih();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        connect();
        try{
            con = DriverManager.getConnection(url+db,"root","");
            stat = con.createStatement();
            String kode = "insert into mtkuliah values('"+kdmk.getText()+"','"
                    +matkul.getText()+"','"+sks.getText()+"')";
            int tambah = stat.executeUpdate(kode);
            if (tambah == 1) {
                JOptionPane.showMessageDialog(this, "Berhasil Menambah Data",
                        "informasi",JOptionPane.INFORMATION_MESSAGE);
                System.out.println("1 Data berhasil ditambahkan");
                bersih();
                kdmk.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Gagal Menambah Data",
                        "informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException se){
            JOptionPane.showMessageDialog(this, "Maaf Kode tersebut sudah ada",
                        "CRITICSAL",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        connect();
        try{
            con = DriverManager.getConnection(url+db,"root","");
            stat = con.createStatement();
            String kode = "delete from mtkuliah where kdmk='"+kdmk.getText()+"'";
            int hapus = stat.executeUpdate(kode);
            if (hapus == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus",
                        "informasi",JOptionPane.INFORMATION_MESSAGE);
                bersih();
                kdmk.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Gagal Menghapus Data",
                        "informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException se){
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Perintah : "
                        +se.getMessage(),"CRITICSAL",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMataKuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMataKuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField kdmk;
    private javax.swing.JTextField matkul;
    private javax.swing.JTextField sks;
    // End of variables declaration//GEN-END:variables
}
